Repository TechUniv2018/ShopSocialFrontEnd, pull requests merged in 2018-03, with the labels that each got.

#21 Integration cart
  public/favicon.ico
  public/index.html
  src/Components/CartModal/CartModal.css
  src/Components/CartModal/CartModal.js
  src/Components/CartProductContainer/CartProductContainer.js
  src/Components/MenuMain/MenuMain.js
  src/Components/ProductDisplay/ProductContainer/ProductContainer.css
  src/Components/ProductDisplay/ProductDisplay.css
Labels: frontend, must have

#24 Feature product category
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/Components/CartModal/CartModal.js
  src/Components/CartProductContainer/CartProductContainer.js
  src/Components/Home/Home.js
  src/Components/ProductCategory/FilterBar/FilterBar.css
  src/Components/ProductCategory/FilterBar/FilterBar.js
  src/Components/ProductCategory/ProductBlock/ProductBlock.css
  src/Components/ProductCategory/ProductBlock/ProductBlock.js
  src/Components/ProductCategory/ProductCategory.css
  src/Components/ProductCategory/ProductCategory.js
  src/Components/ProductCategory/ProductGrid/ProductGrid.css
  src/Components/ProductCategory/ProductGrid/ProductGrid.js
  src/Components/RegisterLoginModal/RegisterLoginModal.css
  src/Components/TestComponents/TestPage.js
  src/index.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/store.js
Labels: enhancement, frontend, must have

#33 Feature cart social
  src/Components/CartModal/CartModal.js
  src/Components/Home/Home.css
  src/Components/MenuMain/MenuMain.css
  src/Components/MenuMain/MenuMain.js
  src/Components/ProductCategory/FilterBar/FilterBar.css
  src/Components/ProductCategory/ProductBlock/ProductBlock.css
  src/Components/ProductCategory/ProductBlock/ProductBlock.js
  src/Components/ProductCategory/ProductBlock/images/product_filler.jpeg
  src/Components/ProductCategory/ProductBlock/images/product_filler.jpg
  src/Components/ProductCategory/ProductCategory.js
  src/Components/ProductCategory/ProductGrid/ProductGrid.css
  src/Components/ProductDisplay/ProductContainer/ProductContainer.js
Labels: enhancement, frontend, must have

#36 CheckOut branch - Completed CheckOut Page
  src/App.js
  src/Components/CartModal/CartModal.js
  src/Components/CheckOut/CheckOut.css
  src/Components/CheckOut/CheckOut.js
  src/Components/CheckOut/CheckoutSuccess.jpg
  src/Components/CheckOut/CheckoutSuccess.png
  src/Components/CheckOut/check.png
  src/Components/CheckOut/check.svg
  src/Components/MenuMain/MenuMain.js
Labels: enhancement, frontend
